# Generated by Django 4.0.1 on 2022-02-11 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('path', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
