# Generated by Django 4.0.1 on 2022-02-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='token_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
