# Generated by Django 4.0.1 on 2022-02-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmodel.people'),
        ),
    ]
