# Generated by Django 4.0.1 on 2022-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0002_faceimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='custom_id',
            field=models.IntegerField(default=0),
        ),
    ]
