# Generated by Django 4.0.1 on 2022-02-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0002_alter_image_token_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='death_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
