# Generated by Django 4.0.1 on 2022-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0004_alter_image_info_alter_image_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='display_name',
        ),
        migrations.AddField(
            model_name='faceimage',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
