# Generated by Django 4.0.1 on 2022-02-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0004_alter_people_first_name_alter_people_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='kids',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='people',
            name='mate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
