# Generated by Django 4.0.1 on 2022-02-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0005_people_kids_people_mate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='kids',
        ),
        migrations.AddField(
            model_name='people',
            name='father',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='people',
            name='mother',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
