# Generated by Django 4.0.1 on 2022-06-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0005_remove_people_display_name_faceimage_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='logid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
