# Generated by Django 4.0.1 on 2022-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0006_remove_people_kids_people_father_people_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='kids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
