# Generated by Django 4.0.1 on 2022-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0007_people_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='info',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
