# Generated by Django 4.0.1 on 2022-02-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0008_people_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='loc_x',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='people',
            name='loc_y',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
